name = "human-bot-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "SESSIONS"
id = "8b74a121b9454bc0898f2a3fa2762f33"